export const FETCH_MOVIE = 'FETCH_MOVIE';

export const SEARCH_OMDB_MOVIE_REQUEST = 'SEARCH_OMDB_MOVIE_REQUEST';
export const SEARCH_OMDB_MOVIE_SUCCESS = 'SEARCH_OMDB_MOVIE_SUCCESS';
export const SEARCH_OMDB_MOVIE_FAILURE = 'SEARCH_OMDB_MOVIE_FAILURE';

export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';

export const LANGUAGE_REQUEST = 'LANGUAGE_REQUEST';
export const LANGUAGE_SUCCESS = 'LANGUAGE_SUCCESS';
export const LANGUAGE_FAILURE = 'LANGUAGE_FAILURE';

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';

export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';

export const GET_LANGUAGES_BY_COUNTRY_REQUEST = 'GET_LANGUAGES_BY_COUNTRY_REQUEST';
export const GET_LANGUAGES_BY_COUNTRY_SUCCESS = 'GET_LANGUAGES_BY_COUNTRY_SUCCESS';
export const GET_LANGUAGES_BY_COUNTRY_FAILURE = 'GET_LANGUAGES_BY_COUNTRY_FAILURE';

export const ADD_TRANSLATION_REQUEST = 'ADD_TRANSLATION_REQUEST';
export const ADD_TRANSLATION_SUCCESS = 'ADD_TRANSLATION_SUCCESS';
export const ADD_TRANSLATION_FAILURE = 'ADD_TRANSLATION_FAILURE';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
