export const FETCH_MOVIE = 'FETCH_MOVIE';

export const SEARCH_OMDB_MOVIE_REQUEST = 'SEARCH_OMDB_MOVIE_REQUEST';
export const SEARCH_OMDB_MOVIE_SUCCESS = 'SEARCH_OMDB_MOVIE_SUCCESS';
export const SEARCH_OMDB_MOVIE_FAILURE = 'SEARCH_OMDB_MOVIE_FAILURE';

export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';

export const LANGUAGE_REQUEST = 'LANGUAGE_REQUEST';
export const LANGUAGE_SUCCESS = 'LANGUAGE_SUCCESS';
export const LANGUAGE_FAILURE = 'LANGUAGE_FAILURE';
